//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceDataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemType
    {
        public ItemType()
        {
            this.Items = new HashSet<Item>();
            this.ItemType1 = new HashSet<ItemType>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<ItemType> ItemType1 { get; set; }
        public virtual ItemType ItemType2 { get; set; }
    }
}
