//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceDataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int Id { get; set; }
        public double Value { get; set; }
        public int ItemId { get; set; }
        public int CurrencyId { get; set; }
        public int UploadByUserId { get; set; }
        public System.DateTime UploadDate { get; set; }
        public System.DateTime EffStartDate { get; set; }
        public System.DateTime EffEndDate { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Item Item { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
